package com.example.movielistapplication.Database.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import com.example.movielistapplication.Database.MovieListDatabase;

import java.util.Objects;

@Entity(tableName = MovieListDatabase.USER_TABLE)
public class User {

  @PrimaryKey(autoGenerate = true)
  private int userId;
  private String username;
  private String password;
  private boolean isAdmin;

  /* Constructor for a user. */
  public User(String username, String password) {
    this.username = username;
    this.password = password;
    this.isAdmin = false; // By default a user is not an admin.
  }

  /* Constructor that takes in a userId, strictly used for testing purposes. */
  @Ignore
  public User (int userId, String username, String password) {
      this.userId = userId;
      this.username = username;
      this.password = password;
      this.isAdmin = false;
  }


  /* Autogenerated getter and setter methods. */
  public int getUserId() {
    return userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public boolean isAdmin() {
    return isAdmin;
  }

  public void setAdmin(boolean admin) {
    isAdmin = admin;
  }


  /* Autogenerated equals and hashCode methods. */
  @Override
  public boolean equals(Object o) {
      if (this == o) {
          return true;
      }
      if (o == null || getClass() != o.getClass()) {
          return false;
      }
    User user = (User) o;
    return userId == user.userId && isAdmin == user.isAdmin && Objects.equals(username,
        user.username) && Objects.equals(password, user.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, username, password, isAdmin);
  }
}

